c_stdlib_version:  # [linux]
  - 2.28           # [linux]

librmm:            # [linux]
  - 25.08          # [linux]

channel_sources:
  - rapidsai,rapidsai-nightly,conda-forge
channel_targets:
  - rapidsai-nightly main
