azure:
  free_disk_space: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
channel_priority: strict
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: false
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  artifact_retention_days: 7
  free_disk_space: true
  upload_packages: true
provider:
  linux: github_actions
  linux_aarch64: github_actions
  osx: github_actions
  win: github_actions
remote_ci_setup:
- conda-forge-ci-setup=4
- conda-build=25.1
test: native
upload_on_branch: main
